export type ListingStatus = "For Sale" | "Pending" | "Sold" | "Wanted" | "Lease";

export type Listing = {
  id: string;
  slug?: string;
  title: string;
  rm: string;
  region: string;
  acres: number;
  pricePerAcre: number;
  avgAssessment: number;
  soilRating: number;
  type: string;
  status: ListingStatus;
  image: string;
  satellite: string;
  coordinates: string;
  latitude?: number | null;
  longitude?: number | null;
  description?: string;
  highlights: string[];
  photos?: Array<{ url: string; caption?: string }>;
  waterSource?: string;
  currentOperator?: string;
  lastSalePrice?: number | null;
  lastSaleDate?: string | null;
  zoning?: string;
  mineralRights?: string;
  encumbrances?: string;
  seoDescription?: string;
  publishedAt?: string | null;
  updatedAt?: string;
};
